name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
jobs:
  docker_action:
  runs-on: ubuntu-latest
  name: Building Docker for scMerge
  steps:
  
  - name: checkout
    uses: actions/checkout@v2
  
  - name: build and push image
    uses: docker/build-push-action@v1.1.0
    with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
      repository: kevinwang09/scmerge ## DockerHub repo
      dockerfile: Dockerfile
      always_pull: true
      tags: latest