on: [push]

jobs:
  docker_action:
    runs-on: ubuntu-latest
    name: Building Docker for scMerge
    steps:
    - name: Publish to Registry
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: kevinwang09/scmerge
        tags: latest